language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly
    
before_install:
    - phpenv config-rm xdebug.ini || true

install:
  - if [[ "$DEPS" = 'high' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS update; fi
  - if [[ "$DEPS" = 'low' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS --prefer-lowest --prefer-stable update; fi
  - if [[ "$DEPS" = 'stable' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS --prefer-stable update; fi
  - ./vendor/bin/psalm --version

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

script: composer check

env:
    matrix:
        - DEPS="low"
        - DEPS="high"
        - DEPS="stable"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-suggest"
        - COMPOSER_DISCARD_CHANGES=1
